### ISSUE TITLE
feature/argument requests: use_intercept, add_refline

### ISSUE THREAD

**Issue by bbolker** [fsolt/dotwhisker#49]
I feel that part of the brilliance of dotwhisker is keeping the plot itself fairly simple, using the flexibility of ggplot2 to let users modify the plot downstream as desired.  However, I'm going to suggest/nominate two optional arguments.

- `drop_intercept` (logical, default should be FALSE for backward compatibility, but perhaps eventually TRUE): the argument here is that the intercept term to a model is (1) often on a very different scale from the other parameters (especially if the predictors have been scaled before fitting a model) (2) often of much less interest than the other parameters.  This is why, for example, `arm::coefplot()` drops the intercept by default.  It is certainly possible to accomplish this by, e.g.

```
library(dwplot); library(broom); library(dplyr)
model %>% tidy() %>% filter(term != "(Intercept)") %>% dwplot
```
but I feel it would (1) be convenient and (2) encourage good statistical/graphical practice to add this option (I know the second argument is a super-slippery slope ...)

- `add_refline` (logical): this one is simpler and maybe less controversial.  If TRUE it would just add `geom_vline(xintercept=0,lty=2)` to the plot.

I can send a pull request if these seem like a good idea (I know I could just send a pull request anyway, and maybe that's the way it's supposed to be done ...)

**Comment by fsolt** [comment]
Thanks, Ben!  These are good ideas.  And, actually, I think the first one is less controversial--dropping the intercept is often important to do.  I think we only overlooked adding an easy way to do it because our initial version of `dwplot` only took tidy dataframes as input, so it was trivial to suggest dropping the intercept before passing it to `dwplot`.  Now that the main way to use `dwplot` is to pass it a list of models, it makes complete sense to add an argument.  I'll be very happy to accept your pull request.

I resist `add_refline` more, though, for two reasons.  First, I think it's easier to demonstrate `+ geom_vline(xintercept=0, lty=2)` in the vignette (and have users actually get it) than the whole `model %>% tidy() %>% filter(term != "(Intercept)") %>% dwplot` thing.  I guess my sense is that `ggplot` has higher mindshare than `dplyr`.  Second, how exactly to depict the reference line is a matter of taste--I just saw a really nice implementation using `theme_grey` and a heavy white line at the x intercept--and keeping the job out of `dwplot` makes it easier for users to customize the line.  To do the same with `add_reline` would then involve adding a subargument for additional color/style options, and it just seems to me too messy when adding a layer is so easy.  Does that seem convincing to you?

**Comment by fsolt** [comment]
I'm going to flip drop_intercept to include_intercept and make FALSE the default.  Frankly, the intercept usually isn't interesting, and this nudges users in the right direction, I think.

**Comment by bbolker** [comment]
maybe `use_intercept` (a tiny bit shorter) ?

**Comment by fsolt** [comment]
Yeah, I pondered the non-backward-compatibility, but I think it's worth it.  We'll just have to flag it in the release notes.
