### ISSUE TITLE
relabel_predictors masks the dot_args function

### ISSUE THREAD

**Issue by ryanburge** [fsolt/dotwhisker#74]
Here's a reproducible example: 

https://gist.github.com/ryanburge/89e08f1966feae687b2ea0cca4cdd1de

**Comment by fsolt** [comment]
Thanks, Ryan, for pointing this out, and for the reprex.  Sorry to take so long to really look at this.  

Unfortunately, I don't see an elegant fix.  When x is `dwplot` output, `relabel_predictors()` just calls `dwplot()` again on the plotted data (which can easily be recovered with `x$data`), but there's no way to get the dot_args back since [one cannot recover a `ggplot` call from a `ggplot` object](https://stackoverflow.com/a/2773704/2620381).  One option would be to add a `dot_args` argument to `relabel_predictors()`, which I started to implement, but when I was writing up the help it just seemed too clunky: "If x is a plot generated by `dwplot()`, a list of arguments specifying changes to the appearance of the dots representing mean estimates.  For supported arguments, see `geom_pointrangeh`" and, you know, don't specify them in your call to `dwplot()`.  Sigh.

There is, otoh, what I _think_ is a fairly straightforward workaround: call `relabel_predictors()` _first_ and _then_ `dwplot()`:

```
regplot <- read_csv("https://raw.githubusercontent.com/ryanburge/cces/master/regplot.csv")

regplot %>%
relabel_predictors(c(treated = "White",
                        age = "Age",
                        educ = "Education",
                        income = "Income",
                        male = "Male",
                        imp = "Importance of Religion",
                        pid = "Republican ID",
                        attend = "Church Attendance",
                        pray = "Frequency of Prayer")) %>%
dwplot(dot_args = list(size = 5))
`
![rplot](https://user-images.githubusercontent.com/6536645/38149046-a373b970-341e-11e8-8e7e-d0fc35766235.png)

**Comment by ryanburge** [comment]
That's a terrific (and easy) solution. Thanks very much.

**Comment by fsolt** [comment]
Actually, inspiration struck a couple of nights ago, and I think I have a much better solution now.  Your original code should work fine with the current dev version:

<img width="1471" alt="screen shot 2018-04-06 at apr 6 1 49 28 pm" src="https://user-images.githubusercontent.com/6536645/38436040-2874b6fe-3999-11e8-81eb-20413e89aec1.png">
